"""empty message

Revision ID: 31e8fac74724
Revises: 3510fead807a
Create Date: 2023-12-19 11:39:20.236115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31e8fac74724"
down_revision: Union[str, None] = "3510fead807a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "athlete",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")
        ),
    )
    op.add_column(
        "athlete",
        sa.Column(
            "last_edited",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.add_column(
        "meet",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")
        ),
    )
    op.add_column(
        "meet",
        sa.Column(
            "last_edited",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.add_column(
        "result",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")
        ),
    )
    op.add_column(
        "result",
        sa.Column(
            "last_edited",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.add_column(
        "team",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")
        ),
    )
    op.add_column(
        "team",
        sa.Column(
            "last_edited",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team", "last_edited")
    op.drop_column("team", "created_at")
    op.drop_column("result", "last_edited")
    op.drop_column("result", "created_at")
    op.drop_column("meet", "last_edited")
    op.drop_column("meet", "created_at")
    op.drop_column("athlete", "last_edited")
    op.drop_column("athlete", "created_at")
    # ### end Alembic commands ###
