"""add race model

Revision ID: 8ca31ca240f3
Revises: dc9d543f28cd
Create Date: 2024-12-19 15:00:46.425346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ca31ca240f3'
down_revision: Union[str, None] = 'dc9d543f28cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=False),
    sa.Column('anet_race_id', sa.Integer(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('race_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('division', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('place_depth', sa.Integer(), nullable=True),
    sa.Column('score_depth', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('result', sa.Column('race_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'result', 'race', ['race_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_column('result', 'race_id')
    op.drop_table('race')
    # ### end Alembic commands ###
