"""fix race anet_id name

Revision ID: 052840a662da
Revises: 8ca31ca240f3
Create Date: 2024-12-19 15:30:50.371797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '052840a662da'
down_revision: Union[str, None] = '8ca31ca240f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('anet_id', sa.Integer(), nullable=False))
    op.drop_column('race', 'anet_race_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('anet_race_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('race', 'anet_id')
    # ### end Alembic commands ###
