"""change name to meet

Revision ID: dc9d543f28cd
Revises: 31e8fac74724
Create Date: 2024-09-27 09:29:22.139932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc9d543f28cd'
down_revision: Union[str, None] = '31e8fac74724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meet', sa.Column('meet', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('meet', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meet', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('meet', 'meet')
    # ### end Alembic commands ###
