"""empty message

Revision ID: 3029a4c1773c
Revises: 4f9db59dc5d8
Create Date: 2023-11-24 23:19:45.679570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3029a4c1773c'
down_revision: Union[str, None] = '4f9db59dc5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simpleresult')
    op.alter_column('athlete', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('athlete', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('simpleresult',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('distance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pr', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sb', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('place', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='simpleresult_pkey')
    )
    # ### end Alembic commands ###
