"""empty message

Revision ID: 3ed2fd85afd4
Revises: ac4a19196bfb
Create Date: 2023-11-25 19:41:54.583768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ed2fd85afd4'
down_revision: Union[str, None] = 'ac4a19196bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('result', 'distance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('result', 'place',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('result', 'pb',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('result', 'sb',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('result', 'sb',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('result', 'pb',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('result', 'place',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('result', 'distance',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
