"""empty message

Revision ID: def3ae8bc799
Revises: 6bf761b42297
Create Date: 2023-11-25 09:50:22.545039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'def3ae8bc799'
down_revision: Union[str, None] = '6bf761b42297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meet', sa.Column('venue', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('meet', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meet', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('meet', 'venue')
    # ### end Alembic commands ###
