race_history = {
    "athlete_data": {
        "anet_id": 5,
        "anet_team_id": 1,
        "first_name": "Alex",
        "last_name": "Skrove",
        "gender": "M",
        "age": None,
    },
    "races": [
        {
            "anet_id": 1994294,
            "anet_meet_id": 3839,
            "anet_team_id": None,
            "anet_athlete_id": 5,
            "first_name": None,
            "last_name": None,
            "team": None,
            "grade": None,
            "result": "18:29",
            "place": 48,
            "pb": True,
            "sb": True,
        }
    ],
}

team_info = {
    "team_data": {
        "name": "New Hope Christian",
        "city": "Grants Pass",
        "state": "OR",
        "mascot": "Warriors",
    },
    "roster": [
        {
            "anet_id": 23678399,
            "first_name": "Alijah",
            "last_name": "Williams",
            "gender": "M",
            "age": None,
        },
        {
            "anet_id": 23843443,
            "first_name": "Colton",
            "last_name": "Wright",
            "gender": "M",
            "age": None,
        },
        {
            "anet_id": 23638350,
            "first_name": "Peighton",
            "last_name": "Wharregard",
            "gender": "M",
            "age": None,
        },
        {
            "anet_id": 23638333,
            "first_name": "Thomas",
            "last_name": "Sheets",
            "gender": "M",
            "age": None,
        },
    ],
    "schedule": [
        {
            "anet_id": 224755,
            "meet": "Myrtle Point Harvest Festival",
            "venue": "Myrtle Point High School",
            "address": "717 4th Street",
            "city": "Myrtle Point",
            "state": "OR",
            "zipcode": 97458,
            "date": "2023-09-09",
        },
        {
            "anet_id": 223847,
            "meet": "Rogue XC Invitational ",
            "venue": "Colver Fields",
            "address": "6100 Colver Rd",
            "city": "Talent",
            "state": "OR",
            "zipcode": 97540,
            "date": "2023-09-16",
        },
        {
            "anet_id": 222689,
            "meet": "Glide Invitational - This Run's For Maynard",
            "venue": "Glide High School",
            "address": None,
            "city": "Glide",
            "state": "OR",
            "zipcode": 97443,
            "date": "2023-09-21",
        },
        {
            "anet_id": 228583,
            "meet": "Project Youth + 5K & 1-Mile",
            "venue": "Project Youth + 5K",
            "address": "2160 NW Vine St",
            "city": "Grants Pass",
            "state": "OR",
            "zipcode": 97526,
            "date": "2023-09-30",
        },
        {
            "anet_id": 222839,
            "meet": "Stan Goodell The Legend Invite",
            "venue": "Hidden Valley High School",
            "address": "651 Murphy Creek Rd.",
            "city": "Grants Pass",
            "state": "OR",
            "zipcode": 97527,
            "date": "2023-10-07",
        },
        {
            "anet_id": 223158,
            "meet": "Days Creek Relays",
            "venue": "Days Creek Charter School",
            "address": "11381 Tiller-Trail Highway",
            "city": "Days Creek",
            "state": "OR",
            "zipcode": 97429,
            "date": "2023-10-10",
        },
        {
            "anet_id": 222083,
            "meet": "Umpqua Invite",
            "venue": "Stewart Park",
            "address": "",
            "city": "Roseburg",
            "state": "OR",
            "zipcode": 97471,
            "date": "2023-10-18",
        },
        {
            "anet_id": 222134,
            "meet": "3A/2A/1A-SD4 District 4 Championships",
            "venue": "Valley of the Rogue State Park",
            "address": None,
            "city": "Gold Hill",
            "state": "OR",
            "zipcode": 97525,
            "date": "2023-10-26",
        },
    ],
}

meet_results = {
    "meet_details": {
        "anet_meet_id": 221788,
        "location": "Ocosta HS",
        "address": "2580 Montesano St. S",
        "city": "Westport",
        "state": "WA",
        "zipcode": 98595,
    },
    "races": [
        {
            "race_details": {
                "anet_race_id": 887562,
                "gender": "F",
                "race_name": "5,000 Meters Varsity",
                "division": "Varsity",
                "place_depth": 7,
                "score_depth": 5,
                "start_time": "2023-09-09T11:00:00",
            },
            "results": [
                {
                    "anet_id": 47723390,
                    "anet_meet_id": 221788,
                    "anet_team_id": 365,
                    "anet_athlete_id": 17569490,
                    "first_name": "Jane",
                    "last_name": "Roloff",
                    "team": "Hoquiam",
                    "grade": 12,
                    "result": "21:12.8",
                    "place": 1,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723391,
                    "anet_meet_id": 221788,
                    "anet_team_id": 315,
                    "anet_athlete_id": 17892506,
                    "first_name": "Melissa",
                    "last_name": "Reiman",
                    "team": "Onalaska",
                    "grade": 11,
                    "result": "24:14",
                    "place": 2,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723392,
                    "anet_meet_id": 221788,
                    "anet_team_id": 580,
                    "anet_athlete_id": 21261557,
                    "first_name": "Joan",
                    "last_name": "Wedam",
                    "team": "Mossyrock",
                    "grade": 10,
                    "result": "24:37",
                    "place": 3,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723393,
                    "anet_meet_id": 221788,
                    "anet_team_id": 595,
                    "anet_athlete_id": 18685992,
                    "first_name": "Kaitlyn",
                    "last_name": "Ganzel",
                    "team": "Willapa Valley",
                    "grade": 11,
                    "result": "26:08",
                    "place": 4,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723394,
                    "anet_meet_id": 221788,
                    "anet_team_id": 595,
                    "anet_athlete_id": 18685949,
                    "first_name": "Jasmine",
                    "last_name": "Solso",
                    "team": "Willapa Valley",
                    "grade": 11,
                    "result": "26:38",
                    "place": 5,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723395,
                    "anet_meet_id": 221788,
                    "anet_team_id": 364,
                    "anet_athlete_id": 15882264,
                    "first_name": "Moli",
                    "last_name": "Luong",
                    "team": "Forks",
                    "grade": 11,
                    "result": "29:23",
                    "place": 6,
                    "pb": False,
                    "sb": True,
                },
                {
                    "anet_id": 47723396,
                    "anet_meet_id": 221788,
                    "anet_team_id": 364,
                    "anet_athlete_id": 15395393,
                    "first_name": "Kendall",
                    "last_name": "Marshall",
                    "team": "Forks",
                    "grade": 12,
                    "result": "29:48",
                    "place": 7,
                    "pb": False,
                    "sb": True,
                },
                {
                    "anet_id": 47723397,
                    "anet_meet_id": 221788,
                    "anet_team_id": 319,
                    "anet_athlete_id": 22184798,
                    "first_name": "Victoria",
                    "last_name": "Sancho",
                    "team": "Winlock",
                    "grade": 10,
                    "result": "30:18",
                    "place": 8,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723398,
                    "anet_meet_id": 221788,
                    "anet_team_id": 319,
                    "anet_athlete_id": 22184777,
                    "first_name": "Natalie",
                    "last_name": "Cardenas Hernandez",
                    "team": "Winlock",
                    "grade": 11,
                    "result": "30:20",
                    "place": 9,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723399,
                    "anet_meet_id": 221788,
                    "anet_team_id": 595,
                    "anet_athlete_id": 23652459,
                    "first_name": "Anna",
                    "last_name": "Perkins",
                    "team": "Willapa Valley",
                    "grade": 10,
                    "result": "32:37",
                    "place": 10,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723400,
                    "anet_meet_id": 221788,
                    "anet_team_id": 588,
                    "anet_athlete_id": 17773396,
                    "first_name": "Jessica",
                    "last_name": "Underhill",
                    "team": "Naselle",
                    "grade": 10,
                    "result": "32:46",
                    "place": 11,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723401,
                    "anet_meet_id": 221788,
                    "anet_team_id": 364,
                    "anet_athlete_id": 15882263,
                    "first_name": "Annika",
                    "last_name": "Leverington",
                    "team": "Forks",
                    "grade": 11,
                    "result": "33:29",
                    "place": 12,
                    "pb": False,
                    "sb": True,
                },
                {
                    "anet_id": 47723402,
                    "anet_meet_id": 221788,
                    "anet_team_id": 314,
                    "anet_athlete_id": 19787516,
                    "first_name": "Kayleen",
                    "last_name": "Weber",
                    "team": "Ocosta",
                    "grade": 10,
                    "result": "34:54",
                    "place": 13,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723403,
                    "anet_meet_id": 221788,
                    "anet_team_id": 365,
                    "anet_athlete_id": 22163941,
                    "first_name": "Hannah",
                    "last_name": "Schlesser",
                    "team": "Hoquiam",
                    "grade": 10,
                    "result": "35:18",
                    "place": 14,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723404,
                    "anet_meet_id": 221788,
                    "anet_team_id": 315,
                    "anet_athlete_id": 23738233,
                    "first_name": "Lilly",
                    "last_name": "Miller",
                    "team": "Onalaska",
                    "grade": 9,
                    "result": "36:09",
                    "place": 15,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723405,
                    "anet_meet_id": 221788,
                    "anet_team_id": 580,
                    "anet_athlete_id": 21515791,
                    "first_name": "Miley",
                    "last_name": "Sanders",
                    "team": "Mossyrock",
                    "grade": 10,
                    "result": "36:10",
                    "place": 16,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723406,
                    "anet_meet_id": 221788,
                    "anet_team_id": 314,
                    "anet_athlete_id": 23752902,
                    "first_name": "Anahi",
                    "last_name": "Sabalsa Valdovinos",
                    "team": "Ocosta",
                    "grade": 11,
                    "result": "40:18",
                    "place": 17,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723407,
                    "anet_meet_id": 221788,
                    "anet_team_id": 364,
                    "anet_athlete_id": 21327566,
                    "first_name": "Erame",
                    "last_name": "Tost",
                    "team": "Forks",
                    "grade": 11,
                    "result": "41:48",
                    "place": 18,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723408,
                    "anet_meet_id": 221788,
                    "anet_team_id": 589,
                    "anet_athlete_id": 23749766,
                    "first_name": "Elise",
                    "last_name": "Barron",
                    "team": "North Beach",
                    "grade": 10,
                    "result": "43:01",
                    "place": 19,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723409,
                    "anet_meet_id": 221788,
                    "anet_team_id": 589,
                    "anet_athlete_id": 19009511,
                    "first_name": "Addison",
                    "last_name": "Baggaley",
                    "team": "North Beach",
                    "grade": 11,
                    "result": "44:44",
                    "place": 20,
                    "pb": False,
                    "sb": False,
                },
            ],
            "team_scores": [],
        },
        {
            "race_details": {
                "anet_race_id": 887560,
                "gender": "M",
                "race_name": "5,000 Meters Varsity",
                "division": "Varsity",
                "place_depth": 7,
                "score_depth": 5,
                "start_time": "2023-09-09T12:00:00",
            },
            "results": [
                {
                    "anet_id": 47723349,
                    "anet_meet_id": 221788,
                    "anet_team_id": 319,
                    "anet_athlete_id": 17583262,
                    "first_name": "Chase",
                    "last_name": "Trodahl",
                    "team": "Winlock",
                    "grade": 12,
                    "result": "19:26",
                    "place": 1,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723350,
                    "anet_meet_id": 221788,
                    "anet_team_id": 365,
                    "anet_athlete_id": 17569516,
                    "first_name": "Ryker",
                    "last_name": "Maxfield",
                    "team": "Hoquiam",
                    "grade": 9,
                    "result": "19:50",
                    "place": 2,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723351,
                    "anet_meet_id": 221788,
                    "anet_team_id": 315,
                    "anet_athlete_id": 17578606,
                    "first_name": "Isaac",
                    "last_name": "Fitch",
                    "team": "Onalaska",
                    "grade": 12,
                    "result": "20:37",
                    "place": 3,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723352,
                    "anet_meet_id": 221788,
                    "anet_team_id": 315,
                    "anet_athlete_id": 17578689,
                    "first_name": "Conner",
                    "last_name": "Blair",
                    "team": "Onalaska",
                    "grade": 12,
                    "result": "20:44",
                    "place": 4,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723353,
                    "anet_meet_id": 221788,
                    "anet_team_id": 588,
                    "anet_athlete_id": 17773425,
                    "first_name": "Derek",
                    "last_name": "Suomela",
                    "team": "Naselle",
                    "grade": 12,
                    "result": "20:51",
                    "place": 5,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723354,
                    "anet_meet_id": 221788,
                    "anet_team_id": 315,
                    "anet_athlete_id": 17892509,
                    "first_name": "Cole",
                    "last_name": "Russon",
                    "team": "Onalaska",
                    "grade": 11,
                    "result": "21:18",
                    "place": 6,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723355,
                    "anet_meet_id": 221788,
                    "anet_team_id": 580,
                    "anet_athlete_id": 17570660,
                    "first_name": "Luis",
                    "last_name": "Contreras",
                    "team": "Mossyrock",
                    "grade": 10,
                    "result": "21:28",
                    "place": 7,
                    "pb": False,
                    "sb": True,
                },
                {
                    "anet_id": 47723356,
                    "anet_meet_id": 221788,
                    "anet_team_id": 315,
                    "anet_athlete_id": 17892514,
                    "first_name": "Taden",
                    "last_name": "Miller",
                    "team": "Onalaska",
                    "grade": 11,
                    "result": "22:12",
                    "place": 8,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723357,
                    "anet_meet_id": 221788,
                    "anet_team_id": 315,
                    "anet_athlete_id": 17578599,
                    "first_name": "Riley",
                    "last_name": "Carter",
                    "team": "Onalaska",
                    "grade": 12,
                    "result": "22:34",
                    "place": 9,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723358,
                    "anet_meet_id": 221788,
                    "anet_team_id": 314,
                    "anet_athlete_id": 17574113,
                    "first_name": "Billy",
                    "last_name": "Burns",
                    "team": "Ocosta",
                    "grade": 10,
                    "result": "22:38",
                    "place": 10,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723359,
                    "anet_meet_id": 221788,
                    "anet_team_id": 365,
                    "anet_athlete_id": 15905368,
                    "first_name": "Oliver",
                    "last_name": "Bryson",
                    "team": "Hoquiam",
                    "grade": 11,
                    "result": "22:48",
                    "place": 11,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723360,
                    "anet_meet_id": 221788,
                    "anet_team_id": 319,
                    "anet_athlete_id": 22184849,
                    "first_name": "Xavier",
                    "last_name": "Sancho-Carrillo",
                    "team": "Winlock",
                    "grade": 11,
                    "result": "22:49",
                    "place": 12,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723361,
                    "anet_meet_id": 221788,
                    "anet_team_id": 580,
                    "anet_athlete_id": 18952123,
                    "first_name": "Ethan",
                    "last_name": "Wedam",
                    "team": "Mossyrock",
                    "grade": 11,
                    "result": "23:11",
                    "place": 13,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723362,
                    "anet_meet_id": 221788,
                    "anet_team_id": 588,
                    "anet_athlete_id": 22118391,
                    "first_name": "Caesar",
                    "last_name": "Garcia",
                    "team": "Naselle",
                    "grade": 9,
                    "result": "23:34",
                    "place": 14,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723363,
                    "anet_meet_id": 221788,
                    "anet_team_id": 589,
                    "anet_athlete_id": 18902177,
                    "first_name": "Sawyer",
                    "last_name": "Reither",
                    "team": "North Beach",
                    "grade": 11,
                    "result": "23:39",
                    "place": 15,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723364,
                    "anet_meet_id": 221788,
                    "anet_team_id": 313,
                    "anet_athlete_id": 23755890,
                    "first_name": "Landon",
                    "last_name": "Engelbertson",
                    "team": "Napavine",
                    "grade": 9,
                    "result": "23:40",
                    "place": 16,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723365,
                    "anet_meet_id": 221788,
                    "anet_team_id": 365,
                    "anet_athlete_id": 17569491,
                    "first_name": "Konlan",
                    "last_name": "Higgins",
                    "team": "Hoquiam",
                    "grade": 12,
                    "result": "23:49",
                    "place": 17,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723366,
                    "anet_meet_id": 221788,
                    "anet_team_id": 314,
                    "anet_athlete_id": 23752921,
                    "first_name": "Michael",
                    "last_name": "Priest",
                    "team": "Ocosta",
                    "grade": 9,
                    "result": "24:01",
                    "place": 18,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723367,
                    "anet_meet_id": 221788,
                    "anet_team_id": 364,
                    "anet_athlete_id": 23760906,
                    "first_name": "Brody",
                    "last_name": "Owen",
                    "team": "Forks",
                    "grade": 11,
                    "result": "24:18",
                    "place": 19,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723368,
                    "anet_meet_id": 221788,
                    "anet_team_id": 314,
                    "anet_athlete_id": 19691441,
                    "first_name": "Ivan",
                    "last_name": "Weber",
                    "team": "Ocosta",
                    "grade": 12,
                    "result": "24:33",
                    "place": 20,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723369,
                    "anet_meet_id": 221788,
                    "anet_team_id": 319,
                    "anet_athlete_id": 17860422,
                    "first_name": "Freddy",
                    "last_name": "Patching",
                    "team": "Winlock",
                    "grade": 9,
                    "result": "24:51",
                    "place": 21,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723370,
                    "anet_meet_id": 221788,
                    "anet_team_id": 319,
                    "anet_athlete_id": 18939444,
                    "first_name": "Jacob",
                    "last_name": "Trodahl",
                    "team": "Winlock",
                    "grade": 9,
                    "result": "25:00",
                    "place": 22,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723371,
                    "anet_meet_id": 221788,
                    "anet_team_id": 364,
                    "anet_athlete_id": 17789418,
                    "first_name": "Klayton",
                    "last_name": "Fletcher",
                    "team": "Forks",
                    "grade": 11,
                    "result": "25:06",
                    "place": 23,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723372,
                    "anet_meet_id": 221788,
                    "anet_team_id": 314,
                    "anet_athlete_id": 14124267,
                    "first_name": "Raymond",
                    "last_name": "Priest",
                    "team": "Ocosta",
                    "grade": 12,
                    "result": "25:26",
                    "place": 24,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723373,
                    "anet_meet_id": 221788,
                    "anet_team_id": 588,
                    "anet_athlete_id": 23748484,
                    "first_name": "Trajen",
                    "last_name": "Ford",
                    "team": "Naselle",
                    "grade": 10,
                    "result": "25:42",
                    "place": 25,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723374,
                    "anet_meet_id": 221788,
                    "anet_team_id": 314,
                    "anet_athlete_id": 23752917,
                    "first_name": "Quinn",
                    "last_name": "Leonard",
                    "team": "Ocosta",
                    "grade": 9,
                    "result": "25:55",
                    "place": 26,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723375,
                    "anet_meet_id": 221788,
                    "anet_team_id": 589,
                    "anet_athlete_id": 23749756,
                    "first_name": "Charlie",
                    "last_name": "Gersitz",
                    "team": "North Beach",
                    "grade": 9,
                    "result": "26:02",
                    "place": 27,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723376,
                    "anet_meet_id": 221788,
                    "anet_team_id": 595,
                    "anet_athlete_id": 17798453,
                    "first_name": "Hunter",
                    "last_name": "Irwin",
                    "team": "Willapa Valley",
                    "grade": 11,
                    "result": "26:04",
                    "place": 28,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723377,
                    "anet_meet_id": 221788,
                    "anet_team_id": 314,
                    "anet_athlete_id": 23752913,
                    "first_name": "Salvador",
                    "last_name": "Medrano",
                    "team": "Ocosta",
                    "grade": 9,
                    "result": "26:52",
                    "place": 29,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723378,
                    "anet_meet_id": 221788,
                    "anet_team_id": 589,
                    "anet_athlete_id": 21220036,
                    "first_name": "Evan",
                    "last_name": "Barron",
                    "team": "North Beach",
                    "grade": 11,
                    "result": "27:06",
                    "place": 30,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723379,
                    "anet_meet_id": 221788,
                    "anet_team_id": 589,
                    "anet_athlete_id": 23749752,
                    "first_name": "Kenneth",
                    "last_name": "Frank",
                    "team": "North Beach",
                    "grade": 9,
                    "result": "27:50",
                    "place": 31,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723380,
                    "anet_meet_id": 221788,
                    "anet_team_id": 588,
                    "anet_athlete_id": 19588061,
                    "first_name": "Reilly",
                    "last_name": "Browning",
                    "team": "Naselle",
                    "grade": 9,
                    "result": "27:54",
                    "place": 32,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723381,
                    "anet_meet_id": 221788,
                    "anet_team_id": 588,
                    "anet_athlete_id": 23748492,
                    "first_name": "Logan",
                    "last_name": "Wirkkala-Scheller",
                    "team": "Naselle",
                    "grade": 9,
                    "result": "28:04",
                    "place": 33,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723382,
                    "anet_meet_id": 221788,
                    "anet_team_id": 580,
                    "anet_athlete_id": 19668164,
                    "first_name": "James",
                    "last_name": "Roberson",
                    "team": "Mossyrock",
                    "grade": 11,
                    "result": "28:15",
                    "place": 34,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723383,
                    "anet_meet_id": 221788,
                    "anet_team_id": 592,
                    "anet_athlete_id": 18934115,
                    "first_name": "Ethan",
                    "last_name": "Worlton",
                    "team": "Raymond",
                    "grade": 12,
                    "result": "28:49",
                    "place": 35,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723384,
                    "anet_meet_id": 221788,
                    "anet_team_id": 319,
                    "anet_athlete_id": 17870260,
                    "first_name": "Xavier",
                    "last_name": "Zeh",
                    "team": "Winlock",
                    "grade": 9,
                    "result": "29:05",
                    "place": 36,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723385,
                    "anet_meet_id": 221788,
                    "anet_team_id": 319,
                    "anet_athlete_id": 17695237,
                    "first_name": "Josh",
                    "last_name": "Dahl",
                    "team": "Winlock",
                    "grade": 11,
                    "result": "29:06",
                    "place": 37,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723386,
                    "anet_meet_id": 221788,
                    "anet_team_id": 580,
                    "anet_athlete_id": 19855988,
                    "first_name": "Tristan",
                    "last_name": "Jenkins",
                    "team": "Mossyrock",
                    "grade": 9,
                    "result": "30:05",
                    "place": 38,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723387,
                    "anet_meet_id": 221788,
                    "anet_team_id": 580,
                    "anet_athlete_id": 22259650,
                    "first_name": "Kayden",
                    "last_name": "Roberson",
                    "team": "Mossyrock",
                    "grade": 9,
                    "result": "30:10",
                    "place": 39,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723388,
                    "anet_meet_id": 221788,
                    "anet_team_id": 319,
                    "anet_athlete_id": 22276897,
                    "first_name": "William",
                    "last_name": "Reid",
                    "team": "Winlock",
                    "grade": 9,
                    "result": "37:40",
                    "place": 40,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723389,
                    "anet_meet_id": 221788,
                    "anet_team_id": 592,
                    "anet_athlete_id": 21932923,
                    "first_name": "Wesley",
                    "last_name": "Erickson",
                    "team": "Raymond",
                    "grade": 12,
                    "result": "41:54",
                    "place": 41,
                    "pb": False,
                    "sb": False,
                },
            ],
            "team_scores": [
                {"place": 1, "anet_team_id": 315, "team": "Onalaska", "points": 25},
                {"place": 2, "anet_team_id": 319, "team": "Winlock", "points": 66},
                {"place": 3, "anet_team_id": 314, "team": "Ocosta", "points": 72},
                {"place": 4, "anet_team_id": 588, "team": "Naselle", "points": 77},
                {"place": 5, "anet_team_id": 580, "team": "Mossyrock", "points": 93},
            ],
        },
        {
            "race_details": {
                "anet_race_id": 887561,
                "gender": "M",
                "race_name": "2,500 Meters Middle School",
                "division": "Middle School",
                "place_depth": 7,
                "score_depth": 5,
                "start_time": "2023-09-09T13:00:00",
            },
            "results": [
                {
                    "anet_id": 47723410,
                    "anet_meet_id": 221788,
                    "anet_team_id": 29422,
                    "anet_athlete_id": 18852912,
                    "first_name": "Kristar",
                    "last_name": "Ashby",
                    "team": "Ocosta",
                    "grade": 8,
                    "result": "8:55",
                    "place": 1,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723411,
                    "anet_meet_id": 221788,
                    "anet_team_id": 29422,
                    "anet_athlete_id": 18928261,
                    "first_name": "Logan",
                    "last_name": "White",
                    "team": "Ocosta",
                    "grade": 8,
                    "result": "9:00",
                    "place": 2,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723412,
                    "anet_meet_id": 221788,
                    "anet_team_id": 29422,
                    "anet_athlete_id": 18852928,
                    "first_name": "Torence",
                    "last_name": "Bonina",
                    "team": "Ocosta",
                    "grade": 8,
                    "result": "9:01",
                    "place": 3,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723413,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20476,
                    "anet_athlete_id": 21450391,
                    "first_name": "Jax",
                    "last_name": "Hudson",
                    "team": "North Beach",
                    "grade": 7,
                    "result": "9:31",
                    "place": 4,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723414,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20505,
                    "anet_athlete_id": 21324893,
                    "first_name": "Peter",
                    "last_name": "Russon",
                    "team": "Onalaska",
                    "grade": 8,
                    "result": "9:32",
                    "place": 5,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723415,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20476,
                    "anet_athlete_id": 21450390,
                    "first_name": "Major",
                    "last_name": "Hudson",
                    "team": "North Beach",
                    "grade": 7,
                    "result": "9:39",
                    "place": 6,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723416,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22145,
                    "anet_athlete_id": 23992416,
                    "first_name": "Greg",
                    "last_name": "Wedam",
                    "team": "Mossyrock",
                    "grade": 8,
                    "result": "9:50",
                    "place": 7,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723417,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22284,
                    "anet_athlete_id": 23748395,
                    "first_name": "Bowen",
                    "last_name": "Burkhalter",
                    "team": "Naselle",
                    "grade": 7,
                    "result": "9:53",
                    "place": 8,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723418,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20505,
                    "anet_athlete_id": 21324894,
                    "first_name": "Thomas",
                    "last_name": "Miller",
                    "team": "Onalaska",
                    "grade": 8,
                    "result": "10:00",
                    "place": 9,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723419,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20476,
                    "anet_athlete_id": 23749779,
                    "first_name": "Brayden",
                    "last_name": "Fry",
                    "team": "North Beach",
                    "grade": 6,
                    "result": "10:06",
                    "place": 10,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723420,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20476,
                    "anet_athlete_id": 23987565,
                    "first_name": "Jack",
                    "last_name": "Glaim",
                    "team": "North Beach",
                    "grade": 8,
                    "result": "10:22",
                    "place": 11,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723421,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22264,
                    "anet_athlete_id": 18848446,
                    "first_name": "Joel",
                    "last_name": "Forler",
                    "team": "Winlock",
                    "grade": 8,
                    "result": "10:29",
                    "place": 12,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723422,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20476,
                    "anet_athlete_id": 21450392,
                    "first_name": "Gabriel",
                    "last_name": "Reinke",
                    "team": "North Beach",
                    "grade": 7,
                    "result": "10:32",
                    "place": 13,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723423,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22768,
                    "anet_athlete_id": 21328592,
                    "first_name": "Gabriel",
                    "last_name": "Rodriguez",
                    "team": "NW Christian (Lacey)",
                    "grade": 8,
                    "result": "10:32.5",
                    "place": 14,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723424,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20505,
                    "anet_athlete_id": 23749232,
                    "first_name": "Jesse",
                    "last_name": "Blair",
                    "team": "Onalaska",
                    "grade": 7,
                    "result": "10:39",
                    "place": 15,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723425,
                    "anet_meet_id": 221788,
                    "anet_team_id": 29422,
                    "anet_athlete_id": 23752936,
                    "first_name": "Cyrus",
                    "last_name": "Pegg",
                    "team": "Ocosta",
                    "grade": 6,
                    "result": "10:48",
                    "place": 16,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723426,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22284,
                    "anet_athlete_id": 23748393,
                    "first_name": "Romain",
                    "last_name": "Garcia",
                    "team": "Naselle",
                    "grade": 7,
                    "result": "11:18",
                    "place": 17,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723427,
                    "anet_meet_id": 221788,
                    "anet_team_id": 29422,
                    "anet_athlete_id": 23776374,
                    "first_name": "Jensen",
                    "last_name": "Morris",
                    "team": "Ocosta",
                    "grade": 7,
                    "result": "11:37",
                    "place": 18,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723428,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20505,
                    "anet_athlete_id": 23722042,
                    "first_name": "Caleb",
                    "last_name": "Srnka",
                    "team": "Onalaska",
                    "grade": 7,
                    "result": "11:38",
                    "place": 19,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723429,
                    "anet_meet_id": 221788,
                    "anet_team_id": 29422,
                    "anet_athlete_id": 21208777,
                    "first_name": "Aiden",
                    "last_name": "Burns",
                    "team": "Ocosta",
                    "grade": 7,
                    "result": "11:41",
                    "place": 20,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723430,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20570,
                    "anet_athlete_id": 23652526,
                    "first_name": "Camden",
                    "last_name": "Wetterauer",
                    "team": "Willapa Valley",
                    "grade": 8,
                    "result": "11:45",
                    "place": 21,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723431,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22768,
                    "anet_athlete_id": 21328444,
                    "first_name": "Samuel",
                    "last_name": "Bode",
                    "team": "NW Christian (Lacey)",
                    "grade": 7,
                    "result": "11:57",
                    "place": 22,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723432,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20476,
                    "anet_athlete_id": 21220007,
                    "first_name": "Dakota",
                    "last_name": "Frank",
                    "team": "North Beach",
                    "grade": 7,
                    "result": "11:58",
                    "place": 23,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723433,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22145,
                    "anet_athlete_id": 22895877,
                    "first_name": "Colin",
                    "last_name": "Bender",
                    "team": "Mossyrock",
                    "grade": 8,
                    "result": "12:07",
                    "place": 24,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723434,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22145,
                    "anet_athlete_id": 23673753,
                    "first_name": "Noah",
                    "last_name": "Ball",
                    "team": "Mossyrock",
                    "grade": 7,
                    "result": "12:13",
                    "place": 25,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723435,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22284,
                    "anet_athlete_id": 23748407,
                    "first_name": "Dane",
                    "last_name": "Benedict",
                    "team": "Naselle",
                    "grade": 7,
                    "result": "12:14",
                    "place": 26,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723436,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22768,
                    "anet_athlete_id": 23761077,
                    "first_name": "Connor",
                    "last_name": "Bowman",
                    "team": "NW Christian (Lacey)",
                    "grade": 8,
                    "result": "12:14.5",
                    "place": 27,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723437,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22768,
                    "anet_athlete_id": 21328573,
                    "first_name": "Joon",
                    "last_name": "Han",
                    "team": "NW Christian (Lacey)",
                    "grade": 6,
                    "result": "13:19",
                    "place": 28,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723438,
                    "anet_meet_id": 221788,
                    "anet_team_id": 29422,
                    "anet_athlete_id": 23776142,
                    "first_name": "Connor",
                    "last_name": "Kautzman",
                    "team": "Ocosta",
                    "grade": 6,
                    "result": "13:54",
                    "place": 29,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723439,
                    "anet_meet_id": 221788,
                    "anet_team_id": 29422,
                    "anet_athlete_id": 23752931,
                    "first_name": "Gehrig",
                    "last_name": "Quinby",
                    "team": "Ocosta",
                    "grade": 6,
                    "result": "14:04",
                    "place": 30,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723440,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20476,
                    "anet_athlete_id": 23749792,
                    "first_name": "Jesiah",
                    "last_name": "Johnson",
                    "team": "North Beach",
                    "grade": 6,
                    "result": "15:35",
                    "place": 31,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723441,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22264,
                    "anet_athlete_id": 22276904,
                    "first_name": "Aiden",
                    "last_name": "Mclane",
                    "team": "Winlock",
                    "grade": 7,
                    "result": "16:09",
                    "place": 32,
                    "pb": True,
                    "sb": True,
                },
            ],
            "team_scores": [
                {"place": 1, "anet_team_id": 29422, "team": "Ocosta", "points": 25},
                {
                    "place": 2,
                    "anet_team_id": 20476,
                    "team": "North Beach",
                    "points": 30,
                },
            ],
        },
        {
            "race_details": {
                "anet_race_id": 887563,
                "gender": "F",
                "race_name": "2,500 Meters Middle School",
                "division": "Middle School",
                "place_depth": 7,
                "score_depth": 5,
                "start_time": "2023-09-09T13:00:00",
            },
            "results": [
                {
                    "anet_id": 47723442,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20505,
                    "anet_athlete_id": 23749218,
                    "first_name": "Tia",
                    "last_name": "Henderson",
                    "team": "Onalaska",
                    "grade": 7,
                    "result": "10:55",
                    "place": 1,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723443,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22284,
                    "anet_athlete_id": 23748387,
                    "first_name": "Kenzie",
                    "last_name": "Larson",
                    "team": "Naselle",
                    "grade": 7,
                    "result": "11:18",
                    "place": 2,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723444,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22145,
                    "anet_athlete_id": 22259990,
                    "first_name": "Alice",
                    "last_name": "Wedam",
                    "team": "Mossyrock",
                    "grade": 7,
                    "result": "11:30",
                    "place": 3,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723445,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22145,
                    "anet_athlete_id": 23673740,
                    "first_name": "Zoella",
                    "last_name": "Zavodsky",
                    "team": "Mossyrock",
                    "grade": 6,
                    "result": "11:59",
                    "place": 4,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723446,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22768,
                    "anet_athlete_id": 23761049,
                    "first_name": "Ellie",
                    "last_name": "Guisewite",
                    "team": "NW Christian (Lacey)",
                    "grade": 5,
                    "result": "12:04",
                    "place": 5,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723447,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22284,
                    "anet_athlete_id": 19588096,
                    "first_name": "Karsen",
                    "last_name": "Green",
                    "team": "Naselle",
                    "grade": 8,
                    "result": "12:32",
                    "place": 6,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723448,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22264,
                    "anet_athlete_id": 21515793,
                    "first_name": "Cheyenne",
                    "last_name": "Zeh",
                    "team": "Winlock",
                    "grade": 7,
                    "result": "13:08",
                    "place": 7,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723449,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20505,
                    "anet_athlete_id": 23721387,
                    "first_name": "Chloe",
                    "last_name": "Haag",
                    "team": "Onalaska",
                    "grade": 7,
                    "result": "13:17",
                    "place": 8,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723450,
                    "anet_meet_id": 221788,
                    "anet_team_id": 29422,
                    "anet_athlete_id": 21495337,
                    "first_name": "Wylee",
                    "last_name": "Keplinger",
                    "team": "Ocosta",
                    "grade": 7,
                    "result": "13:29",
                    "place": 9,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723451,
                    "anet_meet_id": 221788,
                    "anet_team_id": 29422,
                    "anet_athlete_id": 23752939,
                    "first_name": "Alissa",
                    "last_name": "Lamm",
                    "team": "Ocosta",
                    "grade": 7,
                    "result": "13:44",
                    "place": 10,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723452,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20476,
                    "anet_athlete_id": 21450394,
                    "first_name": "Kaiya",
                    "last_name": "Theonnes",
                    "team": "North Beach",
                    "grade": 7,
                    "result": "13:50",
                    "place": 11,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723453,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22145,
                    "anet_athlete_id": 21334179,
                    "first_name": "Avery",
                    "last_name": "Tienhaara",
                    "team": "Mossyrock",
                    "grade": 8,
                    "result": "14:14",
                    "place": 12,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723454,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22284,
                    "anet_athlete_id": 23748390,
                    "first_name": "Ashlyn",
                    "last_name": "Eastham",
                    "team": "Naselle",
                    "grade": 7,
                    "result": "14:26",
                    "place": 13,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723455,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22264,
                    "anet_athlete_id": 23730719,
                    "first_name": "Maggie",
                    "last_name": "Angel",
                    "team": "Winlock",
                    "grade": 6,
                    "result": "14:35",
                    "place": 14,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723456,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20476,
                    "anet_athlete_id": 23749799,
                    "first_name": "Elle",
                    "last_name": "Williams",
                    "team": "North Beach",
                    "grade": 6,
                    "result": "15:03",
                    "place": 15,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723457,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22768,
                    "anet_athlete_id": 23761047,
                    "first_name": "Brooklyn",
                    "last_name": "Duvall",
                    "team": "NW Christian (Lacey)",
                    "grade": 5,
                    "result": "15:09",
                    "place": 16,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723458,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22284,
                    "anet_athlete_id": 23748382,
                    "first_name": "Elisabeth",
                    "last_name": "Green",
                    "team": "Naselle",
                    "grade": 6,
                    "result": "15:24",
                    "place": 17,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723459,
                    "anet_meet_id": 221788,
                    "anet_team_id": 20570,
                    "anet_athlete_id": 21406373,
                    "first_name": "Ellie",
                    "last_name": "Zielesch",
                    "team": "Willapa Valley",
                    "grade": 8,
                    "result": "15:45",
                    "place": 18,
                    "pb": False,
                    "sb": False,
                },
                {
                    "anet_id": 47723460,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22768,
                    "anet_athlete_id": 23761060,
                    "first_name": "Sophia",
                    "last_name": "Green",
                    "team": "NW Christian (Lacey)",
                    "grade": 7,
                    "result": "15:50",
                    "place": 19,
                    "pb": True,
                    "sb": True,
                },
                {
                    "anet_id": 47723461,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22768,
                    "anet_athlete_id": 21328567,
                    "first_name": "Danika",
                    "last_name": "England",
                    "team": "NW Christian (Lacey)",
                    "grade": 8,
                    "result": "16:23",
                    "place": 20,
                    "pb": False,
                    "sb": True,
                },
                {
                    "anet_id": 47723462,
                    "anet_meet_id": 221788,
                    "anet_team_id": 22768,
                    "anet_athlete_id": 21328565,
                    "first_name": "Christiana",
                    "last_name": "Davila-Ledezma",
                    "team": "NW Christian (Lacey)",
                    "grade": 8,
                    "result": "18:29",
                    "place": 21,
                    "pb": False,
                    "sb": True,
                },
            ],
            "team_scores": [
                {
                    "place": 1,
                    "anet_team_id": 22768,
                    "team": "NW Christian (Lacey)",
                    "points": 15,
                }
            ],
        },
    ],
}
