race_history = {
  "athlete_data": {
    "anet_id": 5,
    "anet_team_id": 1,
    "first_name": "Alex",
    "last_name": "Skrove",
    "gender": "M",
    "age": None
  },
  "races": [
    {
      "anet_id": 1994294,
      "anet_meet_id": 3839,
      "anet_team_id": None,
      "anet_athlete_id": 5,
      "first_name": None,
      "last_name": None,
      "team": None,
      "grade": None,
      "result": "18:29",
      "place": 48,
      "pb": True,
      "sb": True,
      "distance": 5000
    }
  ]
}

team_info = {
  "team_data": {
    "anet_id": 9352,
    "name": "Port Jefferson (Earl Vandermeulen)",
    "city": "Port Jefferson",
    "state": "NY",
    "mascot": "Royals"
  },
  "roster": [
    {
      "anet_id": 14306210,
      "first_name": "Arik",
      "last_name": "Sen",
      "gender": "M",
      "age": None
    },
    {
      "anet_id": 15964834,
      "first_name": "Brendan",
      "last_name": "Capodanno",
      "gender": "M",
      "age": None
    },
    {
      "anet_id": 14145186,
      "first_name": "Brennyn",
      "last_name": "Veit",
      "gender": "F",
      "age": None
    },
    {
      "anet_id": 12331025,
      "first_name": "Brian",
      "last_name": "Veit",
      "gender": "M",
      "age": None
    },
    {
      "anet_id": 12454023,
      "first_name": "Caelan",
      "last_name": "Schretzmayer",
      "gender": "F",
      "age": None
    },
    {
      "anet_id": 14231980,
      "first_name": "Christoff",
      "last_name": "Ulinski",
      "gender": "M",
      "age": None
    },
    {
      "anet_id": 10559713,
      "first_name": "Cooper",
      "last_name": "Schoch",
      "gender": "M",
      "age": None
    },
    {
      "anet_id": 20651249,
      "first_name": "Grant",
      "last_name": "Samara",
      "gender": "M",
      "age": None
    },
    {
      "anet_id": 14145188,
      "first_name": "Gray",
      "last_name": "Joyner",
      "gender": "M",
      "age": None
    },
    {
      "anet_id": 12331027,
      "first_name": "Jack",
      "last_name": "Reilly",
      "gender": "M",
      "age": None
    },
    {
      "anet_id": 14214095,
      "first_name": "Jake",
      "last_name": "Rohman",
      "gender": "M",
      "age": None
    },
    {
      "anet_id": 14145189,
      "first_name": "Liam",
      "last_name": "Sproul",
      "gender": "M",
      "age": None
    },
    {
      "anet_id": 12331023,
      "first_name": "Marina",
      "last_name": "Kelley-Renda",
      "gender": "F",
      "age": None
    },
    {
      "anet_id": 12331028,
      "first_name": "Owen",
      "last_name": "Okst",
      "gender": "M",
      "age": None
    },
    {
      "anet_id": 12331029,
      "first_name": "Royce",
      "last_name": "Perera",
      "gender": "M",
      "age": None
    },
    {
      "anet_id": 12331024,
      "first_name": "Sapphire",
      "last_name": "Perera",
      "gender": "F",
      "age": None
    },
    {
      "anet_id": 15964835,
      "first_name": "Teppei",
      "last_name": "Fukuto",
      "gender": "M",
      "age": None
    },
    {
      "anet_id": 14145190,
      "first_name": "Warren",
      "last_name": "Coburn",
      "gender": "M",
      "age": None
    },
    {
      "anet_id": 10790554,
      "first_name": "William",
      "last_name": "Ledezma",
      "gender": "M",
      "age": None
    }
  ],
  "schedule": [
    {
      "anet_id": 175891,
      "meet": "Nike Cross Virtual Week 1",
      "venue": "Virtual XC Season",
      "address": "100 Day Island Rd",
      "city": "Eugene",
      "state": "OR",
      "zipcode": 97401,
      "date": "2020-09-21"
    },
    {
      "anet_id": 179285,
      "meet": "Nike Cross Virtual Week 2",
      "venue": "Virtual XC Season",
      "address": "100 Day Island Rd",
      "city": "Eugene",
      "state": "OR",
      "zipcode": 97401,
      "date": "2020-09-28"
    },
    {
      "anet_id": 179286,
      "meet": "Nike Cross Virtual Week 3",
      "venue": "Virtual XC Season",
      "address": "100 Day Island Rd",
      "city": "Eugene",
      "state": "OR",
      "zipcode": 97401,
      "date": "2020-10-05"
    },
    {
      "anet_id": 179287,
      "meet": "Nike Cross Virtual Week 4",
      "venue": "Virtual XC Season",
      "address": "100 Day Island Rd",
      "city": "Eugene",
      "state": "OR",
      "zipcode": 97401,
      "date": "2020-10-12"
    },
    {
      "anet_id": 179288,
      "meet": "Nike Cross Virtual Week 5",
      "venue": "Virtual XC Season",
      "address": "100 Day Island Rd",
      "city": "Eugene",
      "state": "OR",
      "zipcode": 97401,
      "date": "2020-10-19"
    },
    {
      "anet_id": 179289,
      "meet": "Nike Cross Virtual Week 6",
      "venue": "Virtual XC Season",
      "address": "100 Day Island Rd",
      "city": "Eugene",
      "state": "OR",
      "zipcode": 97401,
      "date": "2020-10-26"
    },
    {
      "anet_id": 179290,
      "meet": "Nike Cross Virtual Week 7",
      "venue": "Virtual XC Season",
      "address": "100 Day Island Rd",
      "city": "Eugene",
      "state": "OR",
      "zipcode": 97401,
      "date": "2020-11-02"
    }
  ]
}

meet_results ={
  "meet_details": {
    "anet_meet_id": 161636,
    "location": "Green Lake",
    "address": "",
    "city": "Seattle",
    "state": "WA",
    "zipcode": 98103
  },
  "teams": [
    {
      "anet_id": 306,
      "name": "The Northwest School",
      "city": None,
      "state": "WA",
      "mascot": None
    }
  ],
  "races": [
    {
      "race_details": {
        "anet_race_id": 675619,
        "gender": "M",
        "race_name": "2 Miles Varsity",
        "division": "Varsity",
        "place_depth": 7,
        "score_depth": 5,
        "start_time": None
      },
      "results": [
        {
          "anet_id": 29180622,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 10462477,
          "first_name": "Keegan",
          "last_name": "Minahan",
          "team": "The Northwest School",
          "grade": None,
          "result": "10:39",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180619,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 10462463,
          "first_name": "Milo",
          "last_name": "Greenberg",
          "team": "The Northwest School",
          "grade": None,
          "result": "10:56",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180617,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 14017634,
          "first_name": "Owen",
          "last_name": "Blaine",
          "team": "The Northwest School",
          "grade": None,
          "result": "11:09",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180621,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 10462475,
          "first_name": "Gabriel",
          "last_name": "McMillen",
          "team": "The Northwest School",
          "grade": None,
          "result": "11:10",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180632,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 12244930,
          "first_name": "Lewis",
          "last_name": "White",
          "team": "The Northwest School",
          "grade": None,
          "result": "11:11",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180616,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 14636543,
          "first_name": "Anders",
          "last_name": "Blaine",
          "team": "The Northwest School",
          "grade": None,
          "result": "11:14",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180627,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 10462480,
          "first_name": "Jarod",
          "last_name": "Polakoff",
          "team": "The Northwest School",
          "grade": None,
          "result": "11:17",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29181021,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 15855224,
          "first_name": "Aidan",
          "last_name": "Coburn",
          "team": "The Northwest School",
          "grade": None,
          "result": "11:38",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29181019,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 15855216,
          "first_name": "Stephen",
          "last_name": "Bleakley-Harris",
          "team": "The Northwest School",
          "grade": None,
          "result": "11:40",
          "place": 0,
          "pb": False,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180630,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 14636589,
          "first_name": "Noah",
          "last_name": "Temam",
          "team": "The Northwest School",
          "grade": None,
          "result": "12:38",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180625,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 11237754,
          "first_name": "Abbott",
          "last_name": "Phinney",
          "team": "The Northwest School",
          "grade": None,
          "result": "12:40",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29181805,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 14636574,
          "first_name": "Atticus",
          "last_name": "Miller",
          "team": "The Northwest School",
          "grade": None,
          "result": "12:46",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180631,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 14017632,
          "first_name": "Merek",
          "last_name": "Weed",
          "team": "The Northwest School",
          "grade": None,
          "result": "13:07",
          "place": 0,
          "pb": False,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29181024,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 8712485,
          "first_name": "Kyle",
          "last_name": "Porter",
          "team": "The Northwest School",
          "grade": None,
          "result": "13:40",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180628,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 10462481,
          "first_name": "Ashwin",
          "last_name": "Raman",
          "team": "The Northwest School",
          "grade": None,
          "result": "14:26",
          "place": 0,
          "pb": False,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180620,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 14017626,
          "first_name": "Kai",
          "last_name": "McAlpin-Godsey",
          "team": "The Northwest School",
          "grade": None,
          "result": "14:30",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180618,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 14017618,
          "first_name": "Alex",
          "last_name": "Bukovec",
          "team": "The Northwest School",
          "grade": None,
          "result": "14:32",
          "place": 0,
          "pb": False,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180626,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 14017635,
          "first_name": "Robbie",
          "last_name": "Piper",
          "team": "The Northwest School",
          "grade": None,
          "result": "14:42",
          "place": 0,
          "pb": False,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180629,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 14017628,
          "first_name": "Keean",
          "last_name": "Stauber",
          "team": "The Northwest School",
          "grade": None,
          "result": "15:04",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29181023,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 14771285,
          "first_name": "Luka",
          "last_name": "Moonen",
          "team": "The Northwest School",
          "grade": None,
          "result": "15:05",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180623,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 12958022,
          "first_name": "Preston",
          "last_name": "Palomino",
          "team": "The Northwest School",
          "grade": None,
          "result": "15:43",
          "place": 0,
          "pb": False,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180633,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 14017638,
          "first_name": "Stone",
          "last_name": "Zhou",
          "team": "The Northwest School",
          "grade": None,
          "result": "16:57",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29181020,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 15855219,
          "first_name": "Darby",
          "last_name": "Brillon",
          "team": "The Northwest School",
          "grade": None,
          "result": "16:57",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29180624,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 14188237,
          "first_name": "Tri",
          "last_name": "Pham",
          "team": "The Northwest School",
          "grade": None,
          "result": "18:23",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29181022,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 10544385,
          "first_name": "Kyle",
          "last_name": "Gustafson",
          "team": "The Northwest School",
          "grade": None,
          "result": "21:12",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        }
      ],
      "team_scores": []
    },
    {
      "race_details": {
        "anet_race_id": 675692,
        "gender": "F",
        "race_name": "2 Miles Varsity",
        "division": "Varsity",
        "place_depth": 7,
        "score_depth": 5,
        "start_time": None
      },
      "results": [
        {
          "anet_id": 29185807,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 10462448,
          "first_name": "Greta",
          "last_name": "Herrington",
          "team": "The Northwest School",
          "grade": None,
          "result": "13:01",
          "place": 0,
          "pb": False,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185802,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 11237706,
          "first_name": "Sasha",
          "last_name": "Balaski",
          "team": "The Northwest School",
          "grade": None,
          "result": "13:02",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185803,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 12872525,
          "first_name": "Haylie",
          "last_name": "Bleakley-Harris",
          "team": "The Northwest School",
          "grade": None,
          "result": "13:40",
          "place": 0,
          "pb": False,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185805,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 17973528,
          "first_name": "Isla",
          "last_name": "Chadsey",
          "team": "The Northwest School",
          "grade": None,
          "result": "14:13",
          "place": 0,
          "pb": False,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185806,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 12244703,
          "first_name": "Iliana",
          "last_name": "Gonzalez",
          "team": "The Northwest School",
          "grade": None,
          "result": "14:15",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185817,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 19161061,
          "first_name": "Maleda",
          "last_name": "Sims",
          "team": "The Northwest School",
          "grade": None,
          "result": "14:50",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185810,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 12244716,
          "first_name": "Charlotte",
          "last_name": "Howell",
          "team": "The Northwest School",
          "grade": None,
          "result": "15:11",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185819,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 15855242,
          "first_name": "Maya",
          "last_name": "Virzi",
          "team": "The Northwest School",
          "grade": None,
          "result": "15:49",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185815,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 12244822,
          "first_name": "Ceci",
          "last_name": "Oshins",
          "team": "The Northwest School",
          "grade": None,
          "result": "15:51",
          "place": 0,
          "pb": False,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185808,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 12244714,
          "first_name": "Reese",
          "last_name": "Heipt",
          "team": "The Northwest School",
          "grade": None,
          "result": "15:55",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185816,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 15855239,
          "first_name": "June",
          "last_name": "Pierson",
          "team": "The Northwest School",
          "grade": None,
          "result": "17:00",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185814,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 12244777,
          "first_name": "Emily",
          "last_name": "Mehalchin",
          "team": "The Northwest School",
          "grade": None,
          "result": "17:10",
          "place": 0,
          "pb": False,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185809,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 15855228,
          "first_name": "Annabelle",
          "last_name": "Howell",
          "team": "The Northwest School",
          "grade": None,
          "result": "19:22",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185818,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 15855240,
          "first_name": "Shelley",
          "last_name": "Tan",
          "team": "The Northwest School",
          "grade": None,
          "result": "19:52",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185813,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 15855236,
          "first_name": "Ansley",
          "last_name": "Mashuda",
          "team": "The Northwest School",
          "grade": None,
          "result": "21:00",
          "place": 0,
          "pb": False,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185811,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 14238795,
          "first_name": "Mingyo",
          "last_name": "Jeong",
          "team": "The Northwest School",
          "grade": None,
          "result": "21:11",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185804,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 15855220,
          "first_name": "Charlotte",
          "last_name": "Bryan",
          "team": "The Northwest School",
          "grade": None,
          "result": "22:00",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        },
        {
          "anet_id": 29185812,
          "anet_meet_id": 161636,
          "anet_team_id": 306,
          "anet_athlete_id": 15855230,
          "first_name": "Charlotte",
          "last_name": "Lee",
          "team": "The Northwest School",
          "grade": None,
          "result": "22:13",
          "place": 0,
          "pb": True,
          "sb": True,
          "distance": None
        }
      ],
      "team_scores": []
    }
  ]
}
schedule = {
  "events": [
    {
      "IDMeet": 224294,
      "Sport": "XC",
      "MeetName": "Forks HS League Meet (CANCELED)",
      "SeasonId": 2023,
      "StartDate": "0001-01-01T00:00:00",
      "EndDate": "2023-09-19T00:00:00",
      "Virtual": False,
      "LocationName": "Olympic Natural Resources Center",
      "StreetAddress": "1455 S Forks Ave",
      "City": "Forks",
      "PostalCode": "98331",
      "State": "WA",
      "OwnerID": 364,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": None,
      "HasResults": 0,
      "LevelMask": 6,
      "HostName": "Forks",
      "MascotUrl": "//lh3.googleusercontent.com/AUH2hZZ7KFJd1HnvbCxwUWO5zaQuN2YUpzeckUG9V9bd6Y6BpCO4ajPePXdkY0zjbVNaEfaKkhQsHPFr08_kMw",
      "Lat": 47.9330028,
      "Long": -124.3944981,
      "score": 0,
      "CalCount": 1,
      "OffDays": "{}",
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 225599,
      "Sport": "XC",
      "MeetName": "Removed",
      "SeasonId": 2023,
      "StartDate": "0001-01-01T00:00:00",
      "EndDate": "2023-10-14T00:00:00",
      "Virtual": False,
      "LocationName": "Ocean Shores Golf Course (parking OS Baptist)",
      "StreetAddress": "625 Point Brown Ave NW",
      "City": "Ocean Shores",
      "PostalCode": "98569",
      "State": "WA",
      "OwnerID": 33216,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": None,
      "HasResults": 0,
      "LevelMask": 4,
      "HostName": "R.A.W. Speed Track",
      "MascotUrl": "//lh3.googleusercontent.com/ViyZQb8Z08_uNXy5Q0-vsG1E6jb1-ZPpNdvHbe-pKsip9NaLr58HLLexE2dXMn7rldyDj1G1BxpTEJwWFrhWWCAu_AfbhzsDf5s",
      "Lat": 46.998239,
      "Long": -124.1579129,
      "score": 0,
      "CalCount": 1,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": 26581,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 163961,
      "Sport": "XC",
      "MeetName": "MHS Time Trial",
      "SeasonId": 2019,
      "StartDate": "2019-09-05T00:00:00",
      "EndDate": "2019-09-05T00:00:00",
      "Virtual": False,
      "LocationName": "Lynndale Park",
      "StreetAddress": "18927 72nd Ave W ",
      "City": "Edmonds",
      "PostalCode": "98036",
      "State": "WA",
      "OwnerID": 481,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": None,
      "HasResults": 1,
      "LevelMask": 4,
      "HostName": "Meadowdale",
      "MascotUrl": "//lh3.googleusercontent.com/XBPIYEvtlZzaWEP8YGjubZ24qWCGrAaeijxCa_5K355l1Fnvs2tG_lVBxVfOWf6x38ac8qHp-z9PTk0ozvF1",
      "Lat": 47.8275671,
      "Long": -122.3318436,
      "score": 0,
      "CalCount": 1,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 163985,
      "Sport": "XC",
      "MeetName": "Reed Park Time Trial",
      "SeasonId": 2019,
      "StartDate": "2019-09-05T00:00:00",
      "EndDate": "2019-09-05T00:00:00",
      "Virtual": False,
      "LocationName": "Reed Park",
      "StreetAddress": "",
      "City": "Ellensburg",
      "PostalCode": "98926",
      "State": "WA",
      "OwnerID": 460,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": None,
      "HasResults": 1,
      "LevelMask": 4,
      "HostName": "Ellensburg",
      "MascotUrl": "//lh3.googleusercontent.com/pjXv-Wkr6f2kcYMWnRrcvY-zgIG5GszCKEwN-KWVzsw7lMGhQnlHXwtl9z2GF3x1D8CV3Fu6CDscc8rMeFTQXQ",
      "Lat": 46.988043,
      "Long": -120.5302539,
      "score": 0,
      "CalCount": 1,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 164883,
      "Sport": "XC",
      "MeetName": "Viking 1 Mile TT",
      "SeasonId": 2019,
      "StartDate": "2019-09-05T00:00:00",
      "EndDate": "2019-09-05T00:00:00",
      "Virtual": False,
      "LocationName": "Saint Edwards State Park",
      "StreetAddress": "14445 Juanita Dr NE",
      "City": "Kenmore",
      "PostalCode": "98028",
      "State": "WA",
      "OwnerID": 494,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": None,
      "HasResults": 1,
      "LevelMask": 4,
      "HostName": "Inglemoor",
      "MascotUrl": "//lh3.googleusercontent.com/cZefUU9--knBJqqNnU5DtC23cHfk7XSDVnmF56tlXaDHbUe18uwr_uvg2rUDs0BKx2CI9bENgHEeUgsR5M-6IA",
      "Lat": 47.7328386,
      "Long": -122.2572382,
      "score": 0,
      "CalCount": 1,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 163818,
      "Sport": "XC",
      "MeetName": "WV Time Trial",
      "SeasonId": 2019,
      "StartDate": "2019-09-05T00:00:00",
      "EndDate": "2019-09-05T00:00:00",
      "Virtual": False,
      "LocationName": "West Valley JH/MS",
      "StreetAddress": "7505 Zier Road",
      "City": "West Valley",
      "PostalCode": "98908",
      "State": "WA",
      "OwnerID": 466,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": None,
      "HasResults": 1,
      "LevelMask": 4,
      "HostName": "West Valley (Yakima)",
      "MascotUrl": "//lh3.googleusercontent.com/3EiYi7jkKIUe2wAO1j7-Jzy6zQH8GJvHLDbD0whfJpNcY05NL0r2o-XALuwFbSD2M_3pAoKiSe3LzwuRfh3aThc",
      "Lat": 46.5765033,
      "Long": -120.6090615,
      "score": 0,
      "CalCount": 1,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 158592,
      "Sport": "XC",
      "MeetName": "Hanford Jamboree",
      "SeasonId": 2019,
      "StartDate": "2019-09-06T00:00:00",
      "EndDate": "2019-09-06T00:00:00",
      "Virtual": False,
      "LocationName": "Leslie Grove Park",
      "StreetAddress": "Snyder Street & Columbia River",
      "City": "Richland",
      "PostalCode": "99354",
      "State": "WA",
      "OwnerID": 461,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": None,
      "HasResults": 1,
      "LevelMask": 4,
      "HostName": "Hanford",
      "MascotUrl": "//lh3.googleusercontent.com/tgDmW8pq2vcO0AeHMG7hfsJQx5Q7bmNsOmv1vtyIc1uESyRh9_CpRfevz-lAHr9aEt1vHFcQQ4Ep1obaeVWM",
      "Lat": 46.30795819999999,
      "Long": -119.2638229,
      "score": 0,
      "CalCount": 7,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 157762,
      "Sport": "XC",
      "MeetName": "Selah Halftime Dash",
      "SeasonId": 2019,
      "StartDate": "2019-09-06T00:00:00",
      "EndDate": "2019-09-06T00:00:00",
      "Virtual": False,
      "LocationName": "Selah HS",
      "StreetAddress": "",
      "City": "Selah",
      "PostalCode": "98942",
      "State": "WA",
      "OwnerID": 463,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": "2019-09-06T00:00:00+00:00",
      "HasResults": 1,
      "LevelMask": 4,
      "HostName": "Selah",
      "MascotUrl": "//lh3.googleusercontent.com/fjE7Wc5NirfOefGB5jXMacE6Ks-lclD1j-SUo9HJd3ngJqYwaVzrO-1Oz6stU_HHmG49G9HgHwkVzlPmLmuv",
      "Lat": 46.663957,
      "Long": -120.52721,
      "score": 0,
      "CalCount": 5,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 164088,
      "Sport": "XC",
      "MeetName": "Team Trial",
      "SeasonId": 2019,
      "StartDate": "2019-09-06T00:00:00",
      "EndDate": "2019-09-06T00:00:00",
      "Virtual": False,
      "LocationName": "Interlake HS",
      "StreetAddress": "16245 NE 24th St",
      "City": "Bellevue",
      "PostalCode": "98008",
      "State": "WA",
      "OwnerID": 407,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": None,
      "HasResults": 1,
      "LevelMask": 4,
      "HostName": "Interlake",
      "MascotUrl": "//lh3.googleusercontent.com/TRUhNOMv_b5NVvEF5CwvEciGJBxK2z9A4hTBvqT45GqBrH0_XAIujaYb-C1bVzJoPAXYU-Xe9pcZcx-sNFTP",
      "Lat": 47.628934,
      "Long": -122.124041,
      "score": 0,
      "CalCount": 1,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "interlakexc.com",
      "Country": "US"
    },
    {
      "IDMeet": 156805,
      "Sport": "XC",
      "MeetName": "TIMBERLINE 2-MILE Jamboree",
      "SeasonId": 2019,
      "StartDate": "2019-09-06T00:00:00",
      "EndDate": "2019-09-06T00:00:00",
      "Virtual": False,
      "LocationName": "Wonderwood Park ",
      "StreetAddress": "5304 32nd Avenue SE",
      "City": "Lacey",
      "PostalCode": "98503 ",
      "State": "WA",
      "OwnerID": 456,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": "2019-09-06T06:59:00+00:00",
      "HasResults": 1,
      "LevelMask": 6,
      "HostName": "Timberline",
      "MascotUrl": "//lh3.googleusercontent.com/kk0zMcRjnC-57fBuqoDiS70iT4Af6fufJvNl7jtu5TnqKTVw-GIS2D6TG0QMrA58rJB7GgmqzdPZJV1ddgTkTA",
      "Lat": 47.02016649999999,
      "Long": -122.8127805,
      "score": 0,
      "CalCount": 11,
      "OffDays": "{}",
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 161093,
      "Sport": "XC",
      "MeetName": "2 mile Alumni Meet @9:45AM",
      "SeasonId": 2019,
      "StartDate": "2019-09-07T00:00:00",
      "EndDate": "2019-09-07T00:00:00",
      "Virtual": False,
      "LocationName": "Wright Park",
      "StreetAddress": "316 South G Street ",
      "City": "Tacoma",
      "PostalCode": "98405",
      "State": "WA",
      "OwnerID": 515,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": None,
      "HasResults": 1,
      "LevelMask": 4,
      "HostName": "Stadium",
      "MascotUrl": "//lh3.googleusercontent.com/GBwbs66VVx9ZNZojptOyRpfQU8gs_Il6Pb8aa3TmLu83zB9wLratj2lnttmwYdVn23Ex8iVWHfUbESDWkFhFOJUzX_4_P5wAwg",
      "Lat": 47.260271,
      "Long": -122.448219,
      "score": 0,
      "CalCount": 1,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 157069,
      "Sport": "XC",
      "MeetName": "2-Mile Time Trial",
      "SeasonId": 2019,
      "StartDate": "2019-09-07T00:00:00",
      "EndDate": "2019-09-07T00:00:00",
      "Virtual": False,
      "LocationName": "Walla Walla Point Park",
      "StreetAddress": "1351 Walla Walla Ave",
      "City": "Wenatchee",
      "PostalCode": "98801",
      "State": "WA",
      "OwnerID": 0,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": None,
      "HasResults": 1,
      "LevelMask": 4,
      "HostName": None,
      "MascotUrl": None,
      "Lat": 47.4435602,
      "Long": -120.3191952,
      "score": 0,
      "CalCount": 1,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 160294,
      "Sport": "XC",
      "MeetName": "Bishop Blanchet Intrasquad",
      "SeasonId": 2019,
      "StartDate": "2019-09-07T00:00:00",
      "EndDate": "2019-09-07T00:00:00",
      "Virtual": False,
      "LocationName": "Green Lake",
      "StreetAddress": "",
      "City": "Seattle",
      "PostalCode": "98103",
      "State": "WA",
      "OwnerID": 415,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": None,
      "HasResults": 1,
      "LevelMask": 4,
      "HostName": "Bishop Blanchet",
      "MascotUrl": "//lh3.googleusercontent.com/09DCg4k02PbEGRnj8M_v3VmA5Wu35YsNDroc0AehA8jZbOOGZQPnwjmQlSgm9G1wnRB56pFH_ka1fWpHh46a7Fi5181dw5fCEVI",
      "Lat": 47.6600087,
      "Long": -122.3425575,
      "score": 0,
      "CalCount": 1,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 161665,
      "Sport": "XC",
      "MeetName": "Davis-3 mile TimeTrail ",
      "SeasonId": 2019,
      "StartDate": "2019-09-07T00:00:00",
      "EndDate": "2019-09-07T00:00:00",
      "Virtual": False,
      "LocationName": "Franklin Park-Yakima",
      "StreetAddress": "2101 Tieton Dr.",
      "City": "Yakima",
      "PostalCode": "98902",
      "State": "WA",
      "OwnerID": 542,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": None,
      "HasResults": 0,
      "LevelMask": 4,
      "HostName": "Davis",
      "MascotUrl": "//lh3.googleusercontent.com/uzZZCDtH1GSdUgnE34M3cQ-R2HYVNjmqPacIYChSw_o7XMlpX5gyTfn8INevxDllU31T7iaEEGxdLEPfPMjgjsxZ77M5rjUJLqQ",
      "Lat": 46.59261009999999,
      "Long": -120.5369041,
      "score": 0,
      "CalCount": 1,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 157244,
      "Sport": "XC",
      "MeetName": "Ellensburg Invitational Relays",
      "SeasonId": 2019,
      "StartDate": "2019-09-07T00:00:00",
      "EndDate": "2019-09-07T00:00:00",
      "Virtual": False,
      "LocationName": "Irene Rhineheart Park",
      "StreetAddress": "",
      "City": "Ellensburg",
      "PostalCode": "98926",
      "State": "WA",
      "OwnerID": 460,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": "2019-09-06T00:39:48+00:00",
      "HasResults": 1,
      "LevelMask": 4,
      "HostName": "Ellensburg",
      "MascotUrl": "//lh3.googleusercontent.com/pjXv-Wkr6f2kcYMWnRrcvY-zgIG5GszCKEwN-KWVzsw7lMGhQnlHXwtl9z2GF3x1D8CV3Fu6CDscc8rMeFTQXQ",
      "Lat": 46.9893526,
      "Long": -120.5729557,
      "score": 0,
      "CalCount": 12,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 158265,
      "Sport": "XC",
      "MeetName": "Marmot Jamboree",
      "SeasonId": 2019,
      "StartDate": "2019-09-07T00:00:00",
      "EndDate": "2019-09-07T00:00:00",
      "Virtual": False,
      "LocationName": "Audubon Park",
      "StreetAddress": "Northwest Blvd & Milton",
      "City": "Spokane",
      "PostalCode": "99205",
      "State": "WA",
      "OwnerID": 0,
      "CalendarLock": 2,
      "UCalendarLock": 0,
      "RegEnd": "2019-09-06T18:15:19+00:00",
      "HasResults": 0,
      "LevelMask": 4,
      "HostName": None,
      "MascotUrl": None,
      "Lat": 47.689903,
      "Long": -117.4538363,
      "score": 0,
      "CalCount": 0,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 161436,
      "Sport": "XC",
      "MeetName": "PHS Intersquad & Family Meet",
      "SeasonId": 2019,
      "StartDate": "2019-09-07T00:00:00",
      "EndDate": "2019-09-07T00:00:00",
      "Virtual": False,
      "LocationName": "Pullman HS",
      "StreetAddress": "510 NW Greyhound Way",
      "City": "Pullman",
      "PostalCode": "99163",
      "State": "WA",
      "OwnerID": 392,
      "CalendarLock": 1,
      "UCalendarLock": 0,
      "RegEnd": None,
      "HasResults": 0,
      "LevelMask": 5,
      "HostName": "Pullman",
      "MascotUrl": "//lh3.googleusercontent.com/7YhJoXnWgtFS0xxAdOx58ATrI3LH7p4lMVXjGpr-MpweUFQJNDVfqG08iU1m6wdud-Zpk3Oe1tNTwXXlWAxS",
      "Lat": 46.7476881,
      "Long": -117.1860253,
      "score": 0,
      "CalCount": 1,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    },
    {
      "IDMeet": 156703,
      "Sport": "XC",
      "MeetName": "Tahoma Coed Relays (Jamboree)",
      "SeasonId": 2019,
      "StartDate": "2019-09-07T00:00:00",
      "EndDate": "2019-09-07T00:00:00",
      "Virtual": False,
      "LocationName": "Lake Wilderness State Park",
      "StreetAddress": "22500 SE 248th Street ",
      "City": "Maple Valley",
      "PostalCode": "98038",
      "State": "WA",
      "OwnerID": 525,
      "CalendarLock": 0,
      "UCalendarLock": 0,
      "RegEnd": None,
      "HasResults": 1,
      "LevelMask": 4,
      "HostName": "Tahoma",
      "MascotUrl": "//lh3.googleusercontent.com/X_M2oxjEMHFhPes78V_cUS7BmNyg9YPC0du7SAqd9mojcrSESk0dNySffwsIhucAtRiOWDnPIajmcVMYV0YOj3Gvf07Qr1d5JRg",
      "Lat": 47.37912,
      "Long": -122.038591,
      "score": 0,
      "CalCount": 43,
      "OffDays": None,
      "Data": None,
      "rsUrl": None,
      "LiveID": None,
      "LivePublished": True,
      "VideoURL": None,
      "Website": "",
      "Country": "US"
    }
  ]
}