race_history = {
    "athlete_data": {
        "anet_id": 5,
        "anet_team_id": 1,
        "first_name": "Alex",
        "last_name": "Skrove",
        "gender": "M",
        "age": None,
    },
    "races": [
        {
            "anet_id": 1994294,
            "anet_meet_id": 3839,
            "anet_team_id": None,
            "anet_athlete_id": 5,
            "first_name": None,
            "last_name": None,
            "team": None,
            "grade": None,
            "result": "18:29",
            "place": 48,
            "pb": True,
            "sb": True,
        }
    ],
}

team_info = {
    "team_data": {
        "name": "New Hope Christian",
        "city": "Grants Pass",
        "state": "OR",
        "mascot": "Warriors",
    },
    "roster": [
        {
            "anet_id": 23678399,
            "first_name": "Alijah",
            "last_name": "Williams",
            "gender": "M",
            "age": None,
        },
        {
            "anet_id": 23843443,
            "first_name": "Colton",
            "last_name": "Wright",
            "gender": "M",
            "age": None,
        },
        {
            "anet_id": 23638350,
            "first_name": "Peighton",
            "last_name": "Wharregard",
            "gender": "M",
            "age": None,
        },
        {
            "anet_id": 23638333,
            "first_name": "Thomas",
            "last_name": "Sheets",
            "gender": "M",
            "age": None,
        },
    ],
    "schedule": [
        {
            "anet_id": 224755,
            "meet": "Myrtle Point Harvest Festival",
            "venue": "Myrtle Point High School",
            "address": "717 4th Street",
            "city": "Myrtle Point",
            "state": "OR",
            "zipcode": 97458,
            "date": "2023-09-09",
        },
        {
            "anet_id": 223847,
            "meet": "Rogue XC Invitational ",
            "venue": "Colver Fields",
            "address": "6100 Colver Rd",
            "city": "Talent",
            "state": "OR",
            "zipcode": 97540,
            "date": "2023-09-16",
        },
        {
            "anet_id": 222689,
            "meet": "Glide Invitational - This Run's For Maynard",
            "venue": "Glide High School",
            "address": None,
            "city": "Glide",
            "state": "OR",
            "zipcode": 97443,
            "date": "2023-09-21",
        },
        {
            "anet_id": 228583,
            "meet": "Project Youth + 5K & 1-Mile",
            "venue": "Project Youth + 5K",
            "address": "2160 NW Vine St",
            "city": "Grants Pass",
            "state": "OR",
            "zipcode": 97526,
            "date": "2023-09-30",
        },
        {
            "anet_id": 222839,
            "meet": "Stan Goodell The Legend Invite",
            "venue": "Hidden Valley High School",
            "address": "651 Murphy Creek Rd.",
            "city": "Grants Pass",
            "state": "OR",
            "zipcode": 97527,
            "date": "2023-10-07",
        },
        {
            "anet_id": 223158,
            "meet": "Days Creek Relays",
            "venue": "Days Creek Charter School",
            "address": "11381 Tiller-Trail Highway",
            "city": "Days Creek",
            "state": "OR",
            "zipcode": 97429,
            "date": "2023-10-10",
        },
        {
            "anet_id": 222083,
            "meet": "Umpqua Invite",
            "venue": "Stewart Park",
            "address": "",
            "city": "Roseburg",
            "state": "OR",
            "zipcode": 97471,
            "date": "2023-10-18",
        },
        {
            "anet_id": 222134,
            "meet": "3A/2A/1A-SD4 District 4 Championships",
            "venue": "Valley of the Rogue State Park",
            "address": None,
            "city": "Gold Hill",
            "state": "OR",
            "zipcode": 97525,
            "date": "2023-10-26",
        },
    ],
}
