"""empty message

Revision ID: 3510fead807a
Revises: ad583e0b8d19
Create Date: 2023-11-25 22:35:30.783876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3510fead807a'
down_revision: Union[str, None] = 'ad583e0b8d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('result', sa.Double(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'result')
    # ### end Alembic commands ###
