"""empty message

Revision ID: 6bf761b42297
Revises: 3029a4c1773c
Create Date: 2023-11-25 09:30:34.931299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6bf761b42297'
down_revision: Union[str, None] = '3029a4c1773c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meet', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('meet', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('meet', sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('meet', sa.Column('zipcode', sa.Integer(), nullable=False))
    op.drop_column('meet', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meet', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('meet', 'zipcode')
    op.drop_column('meet', 'state')
    op.drop_column('meet', 'city')
    op.drop_column('meet', 'address')
    # ### end Alembic commands ###
