"""empty message

Revision ID: ac4a19196bfb
Revises: def3ae8bc799
Create Date: 2023-11-25 15:42:25.029583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac4a19196bfb'
down_revision: Union[str, None] = 'def3ae8bc799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meet', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('meet', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('meet', 'zipcode',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meet', 'zipcode',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('meet', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('meet', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
