"""empty message

Revision ID: ad583e0b8d19
Revises: 3ed2fd85afd4
Create Date: 2023-11-25 22:34:31.303103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad583e0b8d19'
down_revision: Union[str, None] = '3ed2fd85afd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('result', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
